Archy-X/AuraSkills

- src/main/java/com/archyx/aureliumskills/api/AureliumAPI.java
- src/main/java/com/archyx/aureliumskills/data/PlayerData.java
- src/main/java/com/archyx/aureliumskills/mana/ManaManager.java
I have a plugin that integrates with Aurelium skills to use and display mana and mana regeneration rates.
I currently have this logic copy+pasted which is not ideal, I thought it'd be nice for myself and other devs to be able to get the regeneration rate without having to know the secret sauce.
Thank you!
> Add mana regen API, encapsulate mana regen calculation

- src/main/java/com/archyx/aureliumskills/api/event/ManaAbilityReadyEvent.java
- src/main/java/com/archyx/aureliumskills/api/event/ManaAbilityRefreshEvent.java
- src/main/java/com/archyx/aureliumskills/mana/ManaAbilityManager.java
Added this event for a plugin I'm working on that only runs code when an ability's cooldown is finished. Couldn't find anything *documented* about such an event; figured rather than creating my own bukkit task that runs every tick checking all cooldown's it would be more efficient if the plugin just called an event that could be listened to :)
Thanks!
> Add ManaAbilityRefreshEvent

- src/main/java/com/archyx/aureliumskills/api/AureliumAPI.java
* added JavaDocs to setPlugin() that make clear it's for internal usage only
* added a getPlugin() method that returns the instance of AureliumSkills that has been set with setPlugin(). This makes it more convenient for API users to work with non-API classes as it saves them from doing this stuff:
```JAVA
final AureliumSkills aureliumPlugin;
final Plugin probablyAurelium = Bukkit.getPluginManager().getPlugin("AureliumSkills");
try {
aureliumPlugin = (AureliumSkills) probablyAurelium;
} catch (final ClassCastException exception) {
throw new HookException(probablyAurelium, "AureliumSkills wasn't able to be hooked due to another plugin having the same name...");
}
```
> improve AureliumSkills instance API

- pom.xml
- src/main/java/com/archyx/aureliumskills/AureliumSkills.java
- src/main/java/com/archyx/aureliumskills/support/SlimefunSupport.java
- src/main/resources/plugin.yml
Fix the Slimefun block placer duping from #69. 
I added Slimefun to be a soft-dependency and added a listener that listens to the [`BlockPlacerPlaceEvent`](https://github.com/Slimefun/Slimefun4/blob/558bfb5c37fa2983ccc1e06de1f35a0b005a80f5/src/main/java/io/github/thebusybiscuit/slimefun4/api/events/BlockPlacerPlaceEvent.java) from their API. It's called the region manager to add the block of block placer placed for preventing the duping.
> Fix Slimefun block placer duping

- src/main/java/com/archyx/aureliumskills/configuration/Option.java
- src/main/java/com/archyx/aureliumskills/skills/alchemy/AlchemyAbilities.java
- src/main/resources/config.yml
Because `PotionUtil#getDuration()` will default to certain potion lengths, any custom potions with special durations will be effectively overwritten.
This config option, set to false by default to preserve current behaviour, will check if Splash and Lingering Potions have custom effects and opt not to apply Alchemy abilities to them. Such a check isn't required on custom regular potions as they cannot be brewed (doing so causes them to lose their effects anyway).
This should allow better compatibility with other plugins and custom content that uses custom potions.
> Allow custom potions to be ignored

- src/main/java/com/archyx/aureliumskills/api/AureliumAPI.java
Methods on the API already exist to add stat modifiers, but not xp multipliers.
This PR adds the methods to change this.
> Add item multiplier methods to API class

- src/main/java/com/archyx/aureliumskills/AureliumSkills.java
- src/main/java/com/archyx/aureliumskills/lang/AbilityMessage.java
- src/main/java/com/archyx/aureliumskills/lang/ActionBarMessage.java
- src/main/java/com/archyx/aureliumskills/lang/CommandMessage.java
- src/main/java/com/archyx/aureliumskills/lang/LevelerMessage.java
- src/main/java/com/archyx/aureliumskills/lang/ManaAbilityMessage.java
- src/main/java/com/archyx/aureliumskills/lang/MenuMessage.java
- src/main/java/com/archyx/aureliumskills/lang/SkillMessage.java
- src/main/java/com/archyx/aureliumskills/lang/StatMessage.java
- src/main/java/com/archyx/aureliumskills/lang/UnitMessage.java
- src/main/java/com/archyx/aureliumskills/listeners/DamageListener.java
- src/main/java/com/archyx/aureliumskills/mana/Treecapitator.java
- src/main/java/com/archyx/aureliumskills/skills/Skill.java
- src/main/java/com/archyx/aureliumskills/util/armor/ArmorEquipEvent.java
- src/main/java/com/archyx/aureliumskills/util/mechanics/PotionUtil.java
Code cleanup to resolve a few compiler warnings. Fixed enum incomplete switch missing corresponding default label. Fixed several instances of missing `@Override` annotations.
> Code cleanup to resolve a few compiler warnings

- src/main/java/com/archyx/aureliumskills/mana/SharpHook.java
Fixes a logic error where a bitwise AND (&) was used instead of logical AND (&&).
> Logic error in Sharp Hook world validation

- src/main/java/com/archyx/aureliumskills/loot/handler/BlockLootHandler.java
This commit would prevent aurelium skills from overriding a slimefun block drop by blockstorage.
> Cancel Out Block Loot if Slimefun Block

- src/main/java/com/archyx/aureliumskills/region/Region.java
- src/main/java/com/archyx/aureliumskills/region/RegionCoordinate.java
- src/main/java/com/archyx/aureliumskills/region/RegionManager.java
It can cause memory leak when world was unloaded or deleted, now `Region` use weak reference of `World` for removing region when world was unloaded and garbage collected.
> Remove world hard reference from Region

- bukkit/src/main/java/com/archyx/aureliumskills/configuration/Option.java
- bukkit/src/main/java/com/archyx/aureliumskills/listeners/PlayerDeath.java
- bukkit/src/main/resources/config.yml
The pre-existing `reset-skills-on-death` config had the following behavior when true:
- reset all skill levels to 1
- reset all skill XP to 0
This new config value, `reset-xp-on-death`, allows for a subset of that behavior, as follows:
- reset all skill XP to 0
> Configuration - Reset just skill xp on death (reset-xp-on-death)

- bukkit/src/main/java/com/archyx/aureliumskills/skills/archery/ArcheryAbilities.java
Addresses piercing in https://github.com/Archy-X/AureliumSkills/issues/191
Arrows were originally bouncing off of entities if they didn't kill them during a pierce attempt, likely due to invulnerability after being damaged.
Removed the copying of arrows that simulated piercing to get rid of arrows bouncing off entities on non-lethal hits and instead adds 1 to pierceLevel of arrows that do pierce.
Rolls a pierce attempt when an arrow is shot from a bow/crossbow to ensure that the first pierce is successful.
Tested by lining up cows and shooting them with 100% pierce using unenchanted bows and crossbows.
> Fix piercing on non-lethal arrow damage

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/skills/archery/ArcheryAbilities.java
As stated in this [support-request](https://discord.com/channels/732657582313046027/1224006285570216117), the "Retrieval"-Ability would also allow tridents to get retrieved as arrows which it shouldn't.
> Fixed "Retrieval"-Ability detecting tridents as arrows

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/region/BukkitRegionManager.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/region/RegionBlockListener.java
Fixes #243
This will remove the placed sapling/mushroom and everything from the [TreeType](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/TreeType.html) enum from the placed blocks when they grow naturally or via bonemeal, so placed blocks that are converted into natural blocks can give skill XP.
> Remove saplings and every TreeType when they grow from placed blocks

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/hooks/PlaceholderApiProvider.java
Adds support for ability placeholders so the plugin can be more compatible with other plugins that support placeholders/placeholder math.
Adds support for tab completion when you use `/papi parse` command. Just type `/papi parse me %auraskills_` and the tab completion will kick in.
> Ability placeholders and PAPI parse command tabcomplete support

- common/src/main/java/dev/aurelium/auraskills/common/user/User.java
- checked with armor/item modifiers, it doesn't seem to break any internal behavior
- fixes compatibility with 3rd party plugins that are adding stat modifiers over and over again with the same key (almost all of them doing this)
- also tested with latest MythicMobs dev build and with latest MythicLib and MMOItems dev build.
> Fix double reloading on addStatModifier

- api-bukkit/src/main/java/dev/aurelium/auraskills/api/event/loot/LootDropEvent.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/hooks/mythicmobs/MythicMobsHook.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/hooks/mythicmobs/loot/MythicEntityLootParser.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/hooks/mythicmobs/loot/MythicEntitySupplier.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/LootLoader.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/LootManager.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/LootTableManager.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/EntityProperties.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/EntitySupplier.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/VanillaEntityParser.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/VanillaEntitySupplier.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/handler/FishingLootHandler.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/handler/LootHandler.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/parser/CustomEntityParser.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/parser/CustomItemParser.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/parser/CustomParser.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/parser/EntityLootParser.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/type/EntityLoot.java
This PR adds a new entity loot type for fishing (or it can be added to other loot tables as well, it just didn't really make sense).
The caught entity can be a vanilla entity (typically a mob) or a MythicMobs using the `mythicmobs:` prefix. Entity health, damage, and level can also be configured.
The vertical and horizontal velocities are also configurable for fishing but already have default values.
Example configuration in `fishing.yml`:
```yml
type: fishing
pools:
rare:
base_chance: 100
selection_priority: 1
loot:
- type: entity
entity: zombie
name: "&6My Little Zombie"
weight: 50
health: 100
damage: 100
velocity:
horizontal: 1.2
vertical: 1.3
- type: entity
entity: mythicmobs:SkeletonKing
weight: 50
level: 10
```
> Add ability to catch entities with fishing

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/ui/BossBarManager.java
- common/src/main/java/dev/aurelium/auraskills/common/config/Option.java
- common/src/main/resources/config.yml
Here is a brief summary of the changes:
- Removed code duplication: calculating progress as double and casting it to float in `bossBar#progress(float)` method.
```java
double progress = currentXp / levelXp;
if (progress > 1 || progress < 0) {
progress = 1.0;
}
```
- Changed signature of methods `handleNewBossBar` and`handleExistingBossBar` to take progress instead of currentXp and levelXp, and progress as float instead of double
- Added a comment that explains it 
note that the first commit bf80e34 should have been amended but git complained with merge conflicts, so it looks like it got duplicated at 10c922e
> Add boss bar animation when it appears 

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/hooks/BukkitLuckPermsHook.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/user/BukkitUser.java
- common/src/main/resources/config.yml
Luckperms doesn't have any event for permission changes based on the permission nodes contexts.
This means the current cache won't take into account when a multiplier is added/removed based on contexts.
For example, if you use ExtraContexts, or any other built-in LP contexts the cache probably wouldn't work.
I didn't want to remove the entire feature, since it is probably useful for many large servers. Most people only use the server context which doesn't change on the same server. Instead, I made a config option to disable the feature if necessary.
> Add option to disable optimized multiplier permission lookup

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/source/BlockLeveler.java
Currently if other plugins cancel block drops, some drop will still happen due to the fact that an ability is doubling the drop. This pr fixes that and if other plugins cancel the drops then AuraSkills will not try to drop anything
> Respect cancelled drops

- api/src/main/java/dev/aurelium/auraskills/api/registry/NamespacedId.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/hooks/mythicmobs/MythicMobsHook.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/item/BukkitItemRegistry.java
Item registry now returns external plugin items as well from the registered providers, meaning these items can be used in rewards and in loot pools. (And everywhere that uses BukkitItemRegistry#getItem)
I had to store the original key in the NamespacedId as well since plugins usually use case sensitive IDs. 
Item resolver for MM is also added.
> Item resolvers

- .github/workflows/gradle.yml
This PR has CI run on pull requests, irrespective of the base branch selected.
> ci: Run Gradle build on all pull requests

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/requirement/RequirementListener.java
Changed the event priority of BlockBreakEvent in RequirementListener from HIGHEST to LOWEST to ensure requirements are checked before other plugins process the event. This fixes an issue where plugins using NORMAL priority (like Nexo's auto-smelt) would process drops even when the event was later cancelled due to insufficient skill requirements.
- Changed @EventHandler priority to EventPriority.LOWEST- Ensures event cancellation happens before other plugins process drops- Maintains compatibility with plugins that respect event cancellation
TLDR; 
Fixes this https://youtu.be/rx10iCL8rS0
> fix: Change BlockBreakEvent priority to LOWEST to prevent conflicts

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/menus/LevelProgressionMenu.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/menus/StatInfoMenu.java
Two menus are missing the fillItem function call. Resulting in fill items showing their tooltips.
This should fix the issue that's (vaguely) mentioned in #389 which seems to impact two menus.
> Missing fillItem

- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/item/ItemListener.java
This PR fixes the issue opposed in the post on [Discord](https://discord.com/channels/732657582313046027/1392982523876872294) where Valor is not applied in the offhand.
**The issue**:
The issue itself was in the `PlayerSwapItemsEvent`, where the call-order of `#changeItemInSlot` caused the indeed applied valor effect for the offhand to later be unloaded, due to the system saying, that the axe in the mainhand is gone, which caused it to immediately remove it again. Since the mainhand would always be updated second, it has the final say, meaning swapping it back made the appearance as if it only worked in the mainhand.
**The fix**:
Since this should have affected all other bonuses too, I have decided to first unload all effects and then load all effects back in, thinking the small time …
> Fixed issue with off-hand bonuses not being applied

- api/src/main/java/dev/aurelium/auraskills/api/source/type/BlockXpSource.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/AuraSkills.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/listeners/BlockInteractions.java
- bukkit/src/main/java/dev/aurelium/auraskills/bukkit/source/BlockLeveler.java
This allows blocks like beehives/-nests and cauldrons to be used as a source. When trigger is set to "collect" players can use shears (beehive/-nest) or bottles (all three) or buckets (cauldrons) to collect resources and get rewarded.
Interact would otherwise reward for any click made, instead of when resources are collected.
> Added blockTrigger collect
